name: hls4ml-rnn
channels:
  - conda-forge
dependencies:
  - python=3.8
  - jupyterhub
  - pydot
  - graphviz
  - pip
  - pip:
    - jupyter
    - tensorflow==2.4.0
    - tensorflow_datasets
    - git+https://github.com/fastmachinelearning/hls4ml.git@main#egg=hls4ml[profiling]
    - qkeras==0.9.0
    - scikit-learn
    - conifer==0.2b0
